#!/bin/bash
##################################################
# File     : functions
# Purpose  : Cross compile variables
##################################################

LOCAL_PATH=`pwd`
export ARCH="x86_64"
#export ARCH="i686-unknown"
export HOST="${ARCH}-linux-gnu-"
export LOCALINSTALL="${LOCAL_PATH}/_install"
export PREFIX=${LOCALINSTALL}
export CROSS_COMPILE="${ARCH}-linux-gnu-"
export CC="${CROSS_COMPILE}gcc"
export CXX="${CROSS_COMPILE}g++"
export CPP="${CROSS_COMPILE}cpp"
export AR="${CROSS_COMPILE}ar"
export RANLIB="${CROSS_COMPILE}ranlib"
export STRIP="${CROSS_COMPILE}strip"
export OPTIM="-O2"
export CFLAGS="-O0 -g -Wall -D${ARCH} -I${LOCALINSTALL}/include -I${LOCALINSTALL}/usr/include"
export CXXFLAGS="-O0 -g -Wall -D${ARCH} -I${LOCALINSTALL}/include -I${LOCALINSTALL}/usr/include"
export LDFLAGS="-L${LOCALINSTALL}/lib -L${LOCALINSTALL}/usr/lib"


